  
name: "Baselines"
on:
  workflow_dispatch:

jobs:

  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> ensemble_ci
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: baselines_ci
          github_token: ${{ secrets.GITHUB_TOKEN }}
  
  build:
    needs: merge-branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Setup R
      uses: r-lib/actions/setup-r@v1
      
    - name: Install R dependencies
      run: Rscript -e 'install.packages(c("forecast"))' 

    - name: Setup Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - Create Ensembles"
    
    - name: Create Baselines
      env:
        AUTH: ${{ secrets.GITHUBTOKEN }}
      run: | 
        # check out dummy branch
        git checkout baselines_ci
        python3 code/auto_download/auto-download-lanl-covid19.py
        cd ./data-raw/LANL
        Rscript LANL-processing-script.R
        cd ../../
