  
name: "Baselines"
on:
  workflow_dispatch:

jobs:

  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> ensemble_ci
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: baselines_ci
          github_token: ${{ secrets.GITHUB_TOKEN }}
  
  build:
    needs: merge-branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Setup R
      uses: r-lib/actions/setup-r@v1
      
    - name: Install R dependencies
      run: Rscript -e 'install.packages(c("forecast"))' 

    - name: Setup Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - Create Ensembles"
    
    - name: Create Baselines
      env:
        AUTH: ${{ secrets.GITHUB_TOKEN }}
      run: | 
        # check out dummy branch
        git checkout baselines_ci
        cd ./code/baselines
        # create baselines
        Rscript KIT-baseline.R
        Rscript KIT-extrapolation_baseline.R
        Rscript KIT-time_series_baseline.R
        cd ../../
        
        # Push to Github
        git remote rm origin
        git remote add origin https://${AUTH}@github.com/KITmetricslab/covid19-forecast-hub-de.git > /dev/null 2>&1
        git add --all
        git commit -m "Weekly baseline models"
        git push --quiet --set-upstream origin HEAD:baselines_ci
        echo "pushed to github"
