  
name: "Ensemble"
on:
  workflow_dispatch:

jobs:

  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> ensemble_ci
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: ensemble_ci
          github_token: ${{ github.GITHUBTOKEN }}
  
  build:
    needs: merge-branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Setup R
      uses: r-lib/actions/setup-r@v1

    - name: Setup Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - Weekly Forecasts"
