  
name: "Ensemble"
on:
  workflow_dispatch:

jobs:

  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ github.GITHUBTOKEN }}
          source_ref: 'master
          target_branch: 'ensemble_ci'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Setup R
      uses: r-lib/actions/setup-r@v1

    - name: Setup Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - Weekly Forecasts"
