  
name: "Import_EU"
on:
  workflow_dispatch:
  schedule:
   - cron: "0 8 * * 2"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    
    - name: setup python
      uses: actions/setup-python@v2
      with: 
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax

    - run: pip3 install -r ./github-actions/pr_requirements.txt

    - name: Setup R
      uses: r-lib/actions/setup-r@v1

    - name: Setup Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - Create Ensembles"
    
    - name: import files from EU
      env:
        AUTH: ${{ secrets.GITHUB_TOKEN }}
      run: | 
        
        python ./code/hub_transfer/download_eu.py
        cd ./code/hub_transfer/
        # create baselines
        Rscript transfer_forecasts_from_europe.R
        cd ../../
        
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUBTOKEN }}
        commit-message: Import EU forecasts
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: import_eu
        delete-branch: true
        title: 'Import EU forecasts'
        body: |
          Import EU forecasts
        labels: |
          automated pr
        reviewers: jbracher
