  
name: "LANL"
on:
  push:
    branches-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Install requirenments
      run: |
        pip3 install -r github-actions/LANL_Geneva_req.txt
        
    - name: Setup R
      run: |
         sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
         sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/'
         sudo apt update
         sudo apt install r-base
         
    - name: Setup Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - Weekly Forecasts"

    - name: Process LANL
      env:
        AUTH: ${{ secrets.GITHUBTOKEN }}
      run: | 
        # check out dummy branch
        git checkout LANL_actions
        python3 code/auto_download/auto-download-lanl-covid19.py
        cd ./data-raw/LANL
        Rscript LANL-processing-script.R
        cd ../../
      
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUBTOKEN }}
        commit-message: Update Baselines
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: basline
        delete-branch: true
        title: 'Update baselines'
        body: |
          Update baselines
        labels: |
          automated pr
        reviewers: jbracher
