name: "Visualization/Validation/Evaluation"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Setup R
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 51716619E084DAB9
        sudo apt-get install libv8-3.14-dev r-base r-base-dev libudunits2-dev libgdal-dev libgeos-dev libproj-dev fish -y

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Install requirenments
      run: |
        pip3 install -r github-actions/pr_requirements.txt

    - name: Visualization
      run: |
        cd ./app_forecasts_de/code
        python3 ./data_preparation.py
        python3 ./prepare_truth_data.py
        python3 ./add_last_observed.py
        cd ../../code/visualization
        Rscript ./plot_current_forecasts.R	
        cd ../../
        
    - name: Validation
      run: |
        cd ./code/validation
        python3 ./get_commit_dates.py
        python3 ./validate_truth.py
        python3 ./check_truth.py
        cd ../../

    - name: Evaluation
      run: |
        cd ./code/validation
        python3 ./validate_truth.py
        python3 ./check_truth.py

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - Vis Update"
        git commit -m "Daily visualization update" -a
        
    - name: Push changes
      env:
        AUTH: ${{ secrets.GITHUBTOKEN }}
      run: |
        git remote rm origin
        git remote add origin https://${AUTH}@github.com/KITmetricslab/covid19-forecast-hub-de.git > /dev/null 2>&1
        git push --quiet --set-upstream origin HEAD:master
        echo "pushed to github"
